### PR TITLE
change filename

### PR DESCRIPTION
**Pull request by hirosassa**
SSIA

I found this by proof reading on the documents of gokart 1.0.0.

### CODE REVIEW

**Comment by hirosassa** [comment]
@vaaaaanquish @mski-iksm Just fix typo. Please check this.

**Comment by vaaaaanquish** [comment]
LGTM

**Review by vaaaaanquish — APPROVED** [review]

**Comment by mski-iksm** [comment]
LGTM!

**Comment by hirosassa** [comment]
Thanks!

**Pull request merged**
